---
dist: focal
language: ruby
cache: bundler

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2

gemfile:
  - gemfiles/activesupport_4.2.gemfile
  - gemfiles/activesupport_5.0.gemfile
  - gemfiles/activesupport_5.2.gemfile
  - gemfiles/activesupport_6.0.gemfile

matrix:
  exclude:
    - rvm: 2.7.2
      gemfile: gemfiles/activesupport_4.2.gemfile

before_install: 'gem install bundler -v "$(ruby -e "puts RUBY_VERSION.to_f >= 2.7 ? \">= 2.0\" : \"< 2\"")"'

bundler_args: --jobs 3 --retry 3
