module Ebay # :nodoc:
  module Types # :nodoc:
    class ItemSortTypeCode
      extend Enumerable
      extend Enumeration
      ItemID = 'ItemID'
      Price = 'Price'
      StartPrice = 'StartPrice'
      Title = 'Title'
      BidCount = 'BidCount'
      Quantity = 'Quantity'
      StartTime = 'StartTime'
      EndTime = 'EndTime'
      SellerUserID = 'SellerUserID'
      TimeLeft = 'TimeLeft'
      ListingDuration = 'ListingDuration'
      ListingType = 'ListingType'
      CurrentPrice = 'CurrentPrice'
      ReservePrice = 'ReservePrice'
      MaxBid = 'MaxBid'
      BidderCount = 'BidderCount'
      HighBidderUserID = 'HighBidderUserID'
      BuyerUserID = 'BuyerUserID'
      BuyerPostalCode = 'BuyerPostalCode'
      BuyerEmail = 'BuyerEmail'
      SellerEmail = 'SellerEmail'
      TotalPrice = 'TotalPrice'
      WatchCount = 'WatchCount'
      BestOfferCount = 'BestOfferCount'
      QuestionCount = 'QuestionCount'
      ShippingServiceCost = 'ShippingServiceCost'
      FeedbackReceived = 'FeedbackReceived'
      FeedbackLeft = 'FeedbackLeft'
      UserID = 'UserID'
      QuantitySold = 'QuantitySold'
      BestOffer = 'BestOffer'
      QuantityAvailable = 'QuantityAvailable'
      QuantityPurchased = 'QuantityPurchased'
      WonPlatform = 'WonPlatform'
      SoldPlatform = 'SoldPlatform'
      ListingDurationDescending = 'ListingDurationDescending'
      ListingTypeDescending = 'ListingTypeDescending'
      CurrentPriceDescending = 'CurrentPriceDescending'
      ReservePriceDescending = 'ReservePriceDescending'
      MaxBidDescending = 'MaxBidDescending'
      BidderCountDescending = 'BidderCountDescending'
      HighBidderUserIDDescending = 'HighBidderUserIDDescending'
      BuyerUserIDDescending = 'BuyerUserIDDescending'
      BuyerPostalCodeDescending = 'BuyerPostalCodeDescending'
      BuyerEmailDescending = 'BuyerEmailDescending'
      SellerEmailDescending = 'SellerEmailDescending'
      TotalPriceDescending = 'TotalPriceDescending'
      WatchCountDescending = 'WatchCountDescending'
      QuestionCountDescending = 'QuestionCountDescending'
      ShippingServiceCostDescending = 'ShippingServiceCostDescending'
      FeedbackReceivedDescending = 'FeedbackReceivedDescending'
      FeedbackLeftDescending = 'FeedbackLeftDescending'
      UserIDDescending = 'UserIDDescending'
      QuantitySoldDescending = 'QuantitySoldDescending'
      BestOfferCountDescending = 'BestOfferCountDescending'
      QuantityAvailableDescending = 'QuantityAvailableDescending'
      QuantityPurchasedDescending = 'QuantityPurchasedDescending'
      BestOfferDescending = 'BestOfferDescending'
      ItemIDDescending = 'ItemIDDescending'
      PriceDescending = 'PriceDescending'
      StartPriceDescending = 'StartPriceDescending'
      TitleDescending = 'TitleDescending'
      BidCountDescending = 'BidCountDescending'
      QuantityDescending = 'QuantityDescending'
      StartTimeDescending = 'StartTimeDescending'
      EndTimeDescending = 'EndTimeDescending'
      SellerUserIDDescending = 'SellerUserIDDescending'
      TimeLeftDescending = 'TimeLeftDescending'
      WonPlatformDescending = 'WonPlatformDescending'
      SoldPlatformDescending = 'SoldPlatformDescending'
      LeadCount = 'LeadCount'
      NewLeadCount = 'NewLeadCount'
      LeadCountDescending = 'LeadCountDescending'
      NewLeadCountDescending = 'NewLeadCountDescending'
      ClassifiedAdPayPerLeadFee = 'ClassifiedAdPayPerLeadFee'
      ClassifiedAdPayPerLeadFeeDescending = 'ClassifiedAdPayPerLeadFeeDescending'
    end
  end
end

