module Ebay # :nodoc:
  module Types # :nodoc:
    class SellingManagerSoldListingsPropertyTypeCode
      extend Enumerable
      extend Enumeration
      NotPaidNotShipped = 'NotPaidNotShipped'
      PaidNotShipped = 'PaidNotShipped'
      PrintShippingLabel = 'PrintShippingLabel'
      PaidShipped = 'PaidShipped'
      PaidNoFeedback = 'PaidNoFeedback'
      PaymentReminderSendError = 'PaymentReminderSendError'
      PaymentReceivedNotificationSendError = 'PaymentReceivedNotificationSendError'
      RequestForShippingAddressSendError = 'RequestForShippingAddressSendError'
      ShippingNotificationSendError = 'ShippingNotificationSendError'
      PersonalizedEmailsSendError = 'PersonalizedEmailsSendError'
      WinningBuyerNotificationSendError = 'WinningBuyerNotificationSendError'
      FeeCreditRequest = 'FeeCreditRequest'
      PayPalPayment = 'PayPalPayment'
      FeedbackMessageNotSent = 'FeedbackMessageNotSent'
      FeedbackReminderSendError = 'FeedbackReminderSendError'
      NotShipped = 'NotShipped'
      UnpaidItemReminder = 'UnpaidItemReminder'
      EscrowCancelled = 'EscrowCancelled'
      EscrowCompleted = 'EscrowCompleted'
      EscrowInitiated = 'EscrowInitiated'
      EscrowManageRefund = 'EscrowManageRefund'
      EscrowReleasePayment = 'EscrowReleasePayment'
      EscrowShipToBuyer = 'EscrowShipToBuyer'
      EscrowSoldAll = 'EscrowSoldAll'
      ShippedAndAwaitingFeedback = 'ShippedAndAwaitingFeedback'
      InternationalSale = 'InternationalSale'
      EBayGivingWorksDonationOwed = 'eBayGivingWorksDonationOwed'
      PaymentOverDue = 'PaymentOverDue'
      PadiWithPaisaPayEscrow = 'PadiWithPaisaPayEscrow'
      CustomEmailTemplate1SendError = 'CustomEmailTemplate1SendError'
      CustomEmailTemplate2SendError = 'CustomEmailTemplate2SendError'
      CustomEmailTemplate3SendError = 'CustomEmailTemplate3SendError'
      CustomEmailTemplate4SendError = 'CustomEmailTemplate4SendError'
      CustomEmailTemplate5SendError = 'CustomEmailTemplate5SendError'
      CustomEmailTemplate6SendError = 'CustomEmailTemplate6SendError'
      CustomEmailTemplate7SendError = 'CustomEmailTemplate7SendError'
      CustomEmailTemplate8SendError = 'CustomEmailTemplate8SendError'
      CustomEmailTemplate9SendError = 'CustomEmailTemplate9SendError'
      CustomEmailTemplate10SendError = 'CustomEmailTemplate10SendError'
      CustomEmailTemplate11SendError = 'CustomEmailTemplate11SendError'
      CustomEmailTemplate12SendError = 'CustomEmailTemplate12SendError'
      CustomEmailTemplate13SendError = 'CustomEmailTemplate13SendError'
      CustomEmailTemplate14SendError = 'CustomEmailTemplate14SendError'
      CustomEmailTemplate15SendError = 'CustomEmailTemplate15SendError'
      CustomEmailTemplate16SendError = 'CustomEmailTemplate16SendError'
      CustomEmailTemplate17SendError = 'CustomEmailTemplate17SendError'
      CustomEmailTemplate18SendError = 'CustomEmailTemplate18SendError'
      CustomEmailTemplate19SendError = 'CustomEmailTemplate19SendError'
      CustomEmailTemplate20SendError = 'CustomEmailTemplate20SendError'
      ResponseRequiredForReturnCase = 'ResponseRequiredForReturnCase'
    end
  end
end

